// Syncs secrets/google_maps_api_key.json into platform-specific config files.
//
// Usage: dart run tool/sync_maps_api_key.dart
//
// Android reads the JSON directly at build time (no sync needed).
// This script updates iOS xcconfig and web JS config.

import 'dart:convert';
import 'dart:io';

void main() {
  final root = Directory.current;
  if (!File('${root.path}/pubspec.yaml').existsSync()) {
    stderr.writeln('Run from project root.');
    exit(1);
  }

  final secretsFile = File('secrets/google_maps_api_key.json');
  if (!secretsFile.existsSync()) {
    stderr.writeln(
      'Missing secrets/google_maps_api_key.json — copy from '
      'secrets/google_maps_api_key.example.json and add your key.',
    );
    exit(1);
  }

  final json = jsonDecode(secretsFile.readAsStringSync()) as Map<String, dynamic>;
  final apiKey = (json['apiKey'] as String?)?.trim() ?? '';
  if (apiKey.isEmpty || apiKey == 'YOUR_GOOGLE_MAPS_API_KEY') {
    stderr.writeln('Set a valid apiKey in secrets/google_maps_api_key.json');
    exit(1);
  }

  _writeIosSecrets(apiKey);
  _writeWebConfig(apiKey);
  stdout.writeln('Synced Google Maps API key to iOS and Web configs.');
}

void _writeIosSecrets(String apiKey) {
  File('ios/Flutter/Secrets.xcconfig').writeAsStringSync(
    '// Auto-generated by tool/sync_maps_api_key.dart — do not commit\n'
    'GMS_API_KEY=$apiKey\n',
  );
}

void _writeWebConfig(String apiKey) {
  File('web/google_maps_config.js').writeAsStringSync(
    '// Auto-generated by tool/sync_maps_api_key.dart — do not commit\n'
    'window.GOOGLE_MAPS_API_KEY = "$apiKey";\n',
  );
  _writeWebIndexHtml(apiKey);
}

void _writeWebIndexHtml(String apiKey) {
  final indexFile = File('web/index.html');
  final html = indexFile.readAsStringSync();
  const begin = '<!-- GOOGLE_MAPS_SDK:BEGIN';
  const end = '<!-- GOOGLE_MAPS_SDK:END -->';
  final start = html.indexOf(begin);
  final stop = html.indexOf(end);
  if (start < 0 || stop < 0) {
    stderr.writeln('web/index.html missing GOOGLE_MAPS_SDK markers — add them manually.');
    return;
  }
  final replacement =
      '$begin — updated by tool/sync_maps_api_key.dart -->\n'
      '  <script src="https://maps.googleapis.com/maps/api/js?key=$apiKey"></script>\n'
      '  $end';
  indexFile.writeAsStringSync(html.replaceRange(start, stop + end.length, replacement));
}
