// Syncs secrets/google_maps_api_key.json into platform-specific config files.
//
// Usage: dart run tool/sync_maps_api_key.dart
//
// Android reads the JSON directly at build time (no sync needed).
// This script updates iOS xcconfig and web JS config.

import 'dart:convert';
import 'dart:io';

void main() {
  final root = Directory.current;
  if (!File('${root.path}/pubspec.yaml').existsSync()) {
    stderr.writeln('Run from project root.');
    exit(1);
  }

  final secretsFile = File('secrets/google_maps_api_key.json');
  if (!secretsFile.existsSync()) {
    stderr.writeln(
      'Missing secrets/google_maps_api_key.json — copy from '
      'secrets/google_maps_api_key.example.json and add your key.',
    );
    exit(1);
  }

  final json = jsonDecode(secretsFile.readAsStringSync()) as Map<String, dynamic>;
  final apiKey = (json['apiKey'] as String?)?.trim() ?? '';
  if (apiKey.isEmpty || apiKey == 'YOUR_GOOGLE_MAPS_API_KEY') {
    stderr.writeln('Set a valid apiKey in secrets/google_maps_api_key.json');
    exit(1);
  }

  _writeIosSecrets(apiKey);
  _writeWebConfig(apiKey);
  stdout.writeln('Synced Google Maps API key to iOS and Web configs.');
}

void _writeIosSecrets(String apiKey) {
  File('ios/Flutter/Secrets.xcconfig').writeAsStringSync(
    '// Auto-generated by tool/sync_maps_api_key.dart — do not commit\n'
    'GMS_API_KEY=$apiKey\n',
  );
}

void _writeWebConfig(String apiKey) {
  // Classic loader required by google_maps_flutter_web (needs google.maps.MapTypeId).
  // document.write runs during head parse so SDK loads before Flutter bootstrap.
  File('web/google_maps_config.js').writeAsStringSync(
    '// Auto-generated by tool/sync_maps_api_key.dart — do not commit\n'
    'window.GOOGLE_MAPS_API_KEY = "$apiKey";\n'
    'document.write(\'<script src="https://maps.googleapis.com/maps/api/js?key=\' + window.GOOGLE_MAPS_API_KEY + \'"><\\/script>\');\n',
  );
}
